# Generated by Django 3.1.1 on 2020-12-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('description1', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('name1', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=340)),
                ('name2', models.CharField(max_length=23)),
                ('description1', models.CharField(max_length=350)),
                ('name3', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='lesson/')),
            ],
        ),
    ]
