# Generated by Django 3.1.1 on 2020-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
