# Generated by Django 3.1.1 on 2020-12-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_auto_20201216_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='surfing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='surfing/')),
            ],
        ),
    ]
