# Generated by Django 3.1.1 on 2021-01-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_destin4'),
    ]

    operations = [
        migrations.CreateModel(
            name='destin5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='destin5/')),
            ],
        ),
    ]
